services:
    app:
        build: .
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
        restart: always
    mysql:
        image: mysql
        volumes:
            - posts-db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app_db
    phpma:
        image: phpmyadmin
        environment:
            PMA_HOST: mysql 
        ports:
            - 8080:80

volumes:
    posts-db: